- name: Install Docker and required plugins
  hosts: ubuntu
  become: yes

  vars:
    docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
    docker_keyring_path: /etc/apt/keyrings/docker.asc

  tasks:
    - name: Install required dependencies
      apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: yes

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: "{{ docker_gpg_url }}"
        dest: "{{ docker_keyring_path }}"
        mode: '0644'

    - name: Make GPG key readable
      file:
        path: "{{ docker_keyring_path }}"
        mode: '0644'
        state: file

    - name: Get system architecture
      command: dpkg --print-architecture
      register: system_arch
      changed_when: false

    - name: Get Ubuntu version codename
      shell: . /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}"
      register: ubuntu_codename
      changed_when: false

    - name: Add Docker repository to sources.list.d
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: "deb [arch={{ system_arch.stdout }} signed-by={{ docker_keyring_path }}] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable\n"

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker and plugins
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      when: ansible_user != 'root'

    - name: Set Docker daemon config
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            },
            "exec-opts": ["native.cgroupdriver=systemd"]
          }
        owner: root
        group: root
        mode: '0644'
      notify: Restart Docker

  handlers:
    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
        enabled: yes
